// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6IxztYDfNndE81Lr-pU4InKzsN0Nb7Mc',
    appId: '1:682177479135:web:969577e069402d47ccc46a',
    messagingSenderId: '682177479135',
    projectId: 'portefy-11146',
    authDomain: 'portefy-11146.firebaseapp.com',
    storageBucket: 'portefy-11146.firebasestorage.app',
    measurementId: 'G-XF45F84MQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgudcymSA0UIZ4oq2F37inLlvpguHXtfk',
    appId: '1:682177479135:android:4fe897c0ab6d5c69ccc46a',
    messagingSenderId: '682177479135',
    projectId: 'portefy-11146',
    storageBucket: 'portefy-11146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYmN6kQzMAIRTWsaQ_5Q4GUqWW7KCu9wM',
    appId: '1:682177479135:ios:2c150e48cac8f07dccc46a',
    messagingSenderId: '682177479135',
    projectId: 'portefy-11146',
    storageBucket: 'portefy-11146.firebasestorage.app',
    androidClientId: '682177479135-st4ikf8jlbc1dhv2dln85k61a7hkbfu8.apps.googleusercontent.com',
    iosClientId: '682177479135-dua6d7351l88rce3c9sihdqkn75bdsgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.portefy',
  );

}